import team1 from "../../assets/gallery/cbt-01.jpg"
import team2 from "../../assets/gallery/cbt-02.jpg"
import team3 from "../../assets/gallery/cbt-03.jpg"
import team4 from "../../assets/gallery/cbt-04.jpg"
import team5 from "../../assets/gallery/cbt-05.jpg"
import team6 from "../../assets/gallery/cbt-06.jpg"
import team7 from "../../assets/gallery/cbt-07.jpg"
import team8 from "../../assets/gallery/cbt-08.jpg"
import team9 from "../../assets/gallery/cbt-09.jpg"
import team10 from "../../assets/gallery/cbt-10.jpg"
import team11 from "../../assets/gallery/cbt-11.jpg"
import team12 from "../../assets/gallery/cbt-12.jpg"
import team13 from "../../assets/gallery/cbt-13.jpg"
import team14 from "../../assets/gallery/cbt-14.jpg"
import team15 from "../../assets/gallery/cbt-15.jpg"
import team16 from "../../assets/gallery/cbt-16.jpg"
import team17 from "../../assets/gallery/cbt-17.jpg"
import team18 from "../../assets/gallery/cbt_18.jpg"
import team19 from "../../assets/gallery/cbt_19.jpg"
import team20 from "../../assets/gallery/cbt_20.jpg"
import team21 from "../../assets/gallery/cbt_21.jpg"
import video1 from "../../assets/gallery/video_1.mp4"
import video2 from "../../assets/gallery/video_2.mp4"


export const GalleryImage=[team2,team10,team21,team19,team5,video1,team6,team15,team8,team20,team4,team7,video2,team9,team1,team18,team14,team12,team13,team16,team17]